FROM public.ecr.aws/lambda/nodejs:16
# FROM debian:bullseye-slim

WORKDIR /var/task


# RUN apt-get update
# RUN apt-get install zip

RUN echo "HELLOOOOO!"
# docker build -t zipper-layer .
# docker run --rm -v ${PWD}:/var/task -it zipper-layer bash
#
# yum install tar
