####################################################################
# BUILD
# docker build --no-cache -t cbrodski/preper:v2023.1.11.1 -f Dockerfile_ECS_preper  .
# docker build --no-cache -t cbrodski/preper:official_v2 -f Dockerfile_ECS_preper  .

# DEBUG `RUN`
# docker run --env-file .\.env -e ENV=dev cbrodski/preper:v2023.1.11.1
# docker run --env-file .\.env -it -e ENV=dev cbrodski/preper:official_v2 /bin/bash

# PUSH
# docker push cbrodski/preper:official_v2
####################################################################
FROM python:3.10.13-bullseye

LABEL version="1.0"
LABEL description="Runs MicroPreper. Gets recent links from top channels."
LABEL maintainer="your-email@example.com"
LABEL url="https://github.com/Brodski/scraper-dl-vids"
LABEL build_date="2024-01-01"
LABEL vendor="Bski Inc."
LABEL license="Bski"


###########
# Project #
###########
WORKDIR /app
RUN apt update 
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata 
RUN apt install git -y 
RUN git clone https://github.com/Brodski/scraper-dl-vids.git 
COPY cacert-2023-08-22.pem /app/scraper-dl-vids/SSScrapey-rework/cacert-2023-08-22.pem

#######
# Pip #
#######    
WORKDIR /app
RUN apt install curl  -y 
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
    && python get-pip.py pip==23.0.1 \
    && pip --version \
    && rm get-pip.py 
    
################
# Dependencies #
################
WORKDIR /app/scraper-dl-vids/SSScrapey-rework
RUN pip install -r requirements_preper.txt
RUN apt-get install -y firefox-esr
# pip install beautifulsoup4==4.12.2
# pip install selenium==4.16.0
# pip install webdriver-manager==4.0.1
# pip install mysqlclient==2.2.0 


######
# GO #
######
WORKDIR /app/scraper-dl-vids/SSScrapey-rework
CMD echo "NOT DONE!!!!!!!!!!!!" ; \
    git reset --hard origin/master ; \
    git pull origin master --force && \ 
    python kickPreper.py ; \
    echo "DONE!!!!!!!!!!!!" ; 