####################################################################
# BUILD
# docker build --no-cache -t cbrodski/downloader:v2024.1.5.1 -f Dockerfile_ECS_downloader  .
# docker build --no-cache -t cbrodski/downloader:official_v2 -f Dockerfile_ECS_downloader  .

# DEBUG `RUN`
# docker run --env-file .\.env -e ENV=dev cbrodski/downloader:v2024.1.11.1
# docker run --env-file .\.env -e ENV=dev cbrodski/downloader:official_v2
# docker run --env-file .\.env -e ENV=dev -it cbrodski/downloader:official_v2 /bin/bash

# PUSH
# docker push cbrodski/downloader:official_v2
####################################################################
FROM python:3.10.13-bullseye

LABEL version="1.0"
LABEL description="Runs MicroDownloader. Downloads audio, compresses it, puts in s3, ready for Transcriber"
LABEL maintainer="your-email@example.com"
LABEL url="https://github.com/Brodski/scraper-dl-vids"
LABEL build_date="2024-01-01"
LABEL vendor="Bski Inc."
LABEL license="Bski"


###########
# Project #
###########
WORKDIR /app
RUN apt update 
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata 
RUN apt install git -y 
RUN git clone https://github.com/Brodski/scraper-dl-vids.git 
COPY cacert-2023-08-22.pem /app/scraper-dl-vids/SSScrapey-rework/cacert-2023-08-22.pem

#######
# Pip #
#######    
WORKDIR /app
RUN apt install curl  -y 
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
    && python get-pip.py pip==23.0.1 \
    && pip --version \
    && rm get-pip.py 
    
################
# Dependencies #
################
WORKDIR /app/scraper-dl-vids/SSScrapey-rework
RUN pip install -r requirements_downloader.txt \
    && apt-get install ffmpeg -y 
    #  pip install mysqlclient==2.2.0 &&
    #  pip install boto3==1.28.40 &&
    #  pip install yt-dlp==2023.12.30 &&
    #  pip install python-dotenv==1.0.0 &&

######
# GO #
######
WORKDIR /app/scraper-dl-vids/SSScrapey-rework
CMD echo "NOT DONE!!!!!!!!!!!!" ; \
    git reset --hard origin/master && \
    git pull origin master --force && \ 
    python kickDownloader.py ; \
    echo "DONE!!!!!!!!!!!!" ; 