function getLangCode(lang) {
    return langMap[lang]
}

// https://github.com/TiagoDanin/Locale-Codes
// Chat GPT pro helper at bottom
const langMap = {
    "Afar": "aa",
    "Afrikaans": "af",
    "Aghem": "agq",
    "Akan": "ak",
    "Albanian": "sq",
    "Alsatian": "gsw",
    "Amharic": "am",
    "Arabic": "ar",
    "Armenian": "hy",
    "Assamese": "as",
    "Asturian": "ast",
    "Asu": "asa",
    "Azerbaijani (Cyrillic)": "az-Cyrl",
    "Azerbaijani (Latin)": "az",
    "Bafia": "ksf",
    "Bamanankan": "bm",
    "Bamanankan (Latin)": "bm-Latn-ML",
    "Bangla": "bn",
    "Basaa": "bas",
    "Bashkir": "ba",
    "Basque": "eu",
    "Belarusian": "be",
    "Bemba": "bem",
    "Bena": "bez",
    "Blin": "byn",
    "Bodo": "brx",
    "Bosnian (Cyrillic)": "bs-Cyrl",
    "Bosnian (Latin)": "bs-Latn",
    "Breton": "br",
    "Bulgarian": "bg",
    "Burmese": "my",
    "Catalan": "ca",
    "Cebuano": "ceb",
    "Cebuan (Latin)": "ceb-Latn",
    "Central Atlas Tamazight (Latin)": "tzm-Latn-",
    "Central Kurdish": "ku",
    "Chakma": "ccp",
    "Chechen": "cd-RU",
    "Cherokee": "chr",
    "Chiga": "cgg",
    "Chinese (Simplified)": "zh-Hans",
    "Chinese (Traditional)": "zh-Hant",
    "Church Slavic": "cu-RU",
    "Congo Swahili": "swc",
    "Cornish": "kw",
    "Corsican": "co",
    "Croatian": "hr,",
    "Croatian (Latin)": "hr-BA",
    "Czech": "cs",
    "Danish": "da",
    "Dari": "prs",
    "Divehi": "dv",
    "Duala": "dua",
    "Dutch": "nl",
    "Dzongkha": "dz",
    "Embu": "ebu",
    "English": "en-US",
    "Esperanto": "eo",
    "Estonian": "et",
    "Ewe": "ee",
    "Ewondo": "ewo",
    "Faroese": "fo",
    "Filipino": "fil",
    "Finnish": "fi",
    "French": "fr",
    "Frisian": "fy",
    "Friulian": "fur",
    "Fulah": "ff",
    "Fulah (Latin)": "ff-Latn",
    "Fulah": "ff-CM",
    "Fulah (Latin)": "ff-Latn-CM",
    "Fulah": "ff-GN",
    "Fulah (Latin)": "ff-Latn-GN",
    "Fulah": "ff-MR",
    "Fulah (Latin)": "ff-Latn-MR",
    "Fulah": "ff-NG",
    "Fulah (Latin)": "ff-Latn-NG",
    "Fulah": "ff-Latn-SN",
    "Fulah (Latin)": "ff-Latn-SL",
    "Galician": "gl",
    "Ganda": "lg",
    "Georgian": "ka",
    "German": "de",
    "Greek": "el",
    "Greenlandic": "kl",
    "Guarani": "gn",
    "Gujarati": "gu",
    "Gusii": "guz",
    "Hausa (Latin)": "ha",
    "Hawaiian": "haw",
    "Hebrew": "he",
    "Hindi": "hi",
    "Hungarian": "hu",
    "Icelandic": "is",
    "Igbo": "ig",
    "Indonesian": "id",
    "Interlingua": "ia",
    "Inuktitut (Latin)": "iu",
    "Inuktitut (Syllabics)": "iu-Cans",
    "Irish": "ga",
    "Italian": "it",
    "Japanese": "ja",
    "Javanese": "jv",
    "Jola-Fonyi": "dyo",
    "Kabuverdianu": "kea",
    "Kabyle": "kab",
    "Kako": "kkj",
    "Kalenjin": "kln",
    "Kamba": "kam",
    "Kannada": "kn",
    "Kashmiri": "ks",
    "Kazakh": "kk",
    "Khmer": "km",
    "K'iche": "quc",
    "Kikuyu": "ki",
    "Kinyarwanda": "rw",
    "Kiswahili": "sw",
    "Konkani": "kok",
    "Korean": "ko",
    "Koyra Chiini": "khq",
    "Koyraboro Senni": "ses",
    "Kwasio": "nmg",
    "Kyrgyz": "ky",
    "Kurdish": "ku-Arab-IR",
    "Lakota": "lkt",
    "Langi": "lag",
    "Lao": "lo",
    "Latvian": "lv",
    "Lingala": "ln",
    "Lithuanian": "lt",
    "Low German": "nds",
    "Lower Sorbian": "dsb",
    "Luba-Katanga": "lu",
    "Luo": "luo",
    "Luxembourgish": "lb",
    "Luyia": "luy",
    "Macedonian": "mk",
    "Machame": "jmc",
    "Makhuwa-Meetto": "mgh",
    "Makonde": "kde",
    "Malagasy": "mg",
    "Malay": "ms",
    "Malayalam": "ml",
    "Maltese": "mt",
    "Manx": "gv",
    "Maori": "mi",
    "Mapudungun": "arn",
    "Marathi": "mr",
    "Masai": "mas",
    "Mazanderani": "mzn-IR",
    "Meru": "mer",
    "Meta'": "mgo",
    "Mohawk": "moh",
    "Mongolian (Cyrillic)": "mn",
    "Mongolian (Traditional Mongolian)": "mn-Mong",
    "Morisyen": "mfe",
    "Mundang": "mua",
    "N'ko": "nqo",
    "Nama": "naq",
    "Nepali": "ne",
    "Ngiemboon": "nnh",
    "Ngomba": "jgo",
    "Northern Luri": "lrc-IQ",
    "North Ndebele": "nd",
    "Norwegian (Bokmal)": "no",
    "Norwegian (Nynorsk)": "nn",
    "Norwegian Bokmål": "nb-SJ",
    "Nuer": "nus",
    "Nyankole": "nyn",
    "Occitan": "oc",
    "Odia": "or",
    "Oromo": "om",
    "Ossetian": "os",
    "Pashto": "ps",
    "Persian": "fa",
    "Polish": "pl",
    "Portuguese": "pt",
    "Prussian": "prg-001",
    "Pseudo Language": "qps-ploca",
    "Punjabi": "pa",
    "Quechua": "quz",
    "Ripuarian": "ksh",
    "Romanian": "ro",
    "Romansh": "rm",
    "Rombo": "rof",
    "Rundi": "rn",
    "Russian": "ru",
    "Rwa": "rwk",
    "Saho": "ssy",
    "Sakha": "sah",
    "Samburu": "saq",
    "Sami (Inari)": "smn",
    "Sami (Lule)": "smj",
    "Sami (Northern)": "se",
    "Sami (Skolt)": "sms",
    "Sami (Southern)": "sma",
    "Sango": "sg",
    "Sangu": "sbp",
    "Sanskrit": "sa",
    "Scottish Gaelic": "gd",
    "Sena": "seh",
    "Serbian (Cyrillic)": "sr-Cyrl",
    "Serbian (Latin)": "sr-Latn",
    "Sesotho sa Leboa": "nso",
    "Setswana": "tn",
    "Shambala": "ksb",
    "Shona": "sn",
    "Sindhi": "sd",
    "Sinhala": "si",
    "Slovak": "sk",
    "Slovenian": "sl",
    "Soga": "xog",
    "Somali": "so",
    "Sotho": "st",
    "South Ndebele": "nr",
    "Southern Sotho": "st-LS",
    "Spanish": "es",
    "Standard Moroccan Tamazight": "zgh",
    "Swati": "ss",
    "Swedish": "sv",
    "Syriac": "syr",
    "Tachelhit": "shi",
    "Tachelhit (Latin)": "shi-Latn",
    "Taita": "dav",
    "Tajik (Cyrillic)": "tg",
    "Tamazight (Latin)": "tzm",
    "Tamil": "ta",
    "Tasawaq": "twq",
    "Tatar": "tt",
    "Telugu": "te",
    "Teso": "teo",
    "Thai": "th",
    "Tibetan": "bo",
    "Tigre": "tig",
    "Tigrinya": "ti",
    "Tongan": "to",
    "Tsonga": "ts",
    "Turkish": "tr",
    "Turkmen": "tk",
    "Ukrainian": "uk",
    "Upper Sorbian": "hsb",
    "Urdu": "ur",
    "Uyghur": "ug",
    "Uzbek": "uz-Arab",
    "Uzbek (Cyrillic)": "uz-Cyrl",
    "Uzbek (Latin)": "uz",
    "Vai": "vai",
    "Vai (Latin)": "vai-Latn-LR",
    "Valencian": "ca-ES-",
    "Venda": "ve"
}

module.exports = getLangCode;


/*
Let's approach this with a more manual method using Google Sheets' built-in tools:
Step-by-Step Method to Remove Quasi-Duplicates

1. Add a Helper Column:
    . In column C (or any other empty column), enter the following formula in the first row of data (C2):

    =IF(A2=A1, "Duplicate", "Keep")

    . Drag this formula down to apply it to all rows. This formula will mark rows as "Duplicate" if the language in
    the current row matches the language in the previous row.
2. Filter the Data:
    · Select all your data (Columns A, B, and C).
    . Go to `Data > Create a filter'.
    . In the filter dropdown for the helper column (Column C), uncheck "Duplicate," leaving only "Keep" checked.
    This will filter out all the duplicate rows.
3. Delete the Duplicate Rows:
    . Once the filter is applied, select all the visible rows (which are the rows marked as "Keep").
    . Right-click and select `Delete selected rows'.
    · Remove the filter to see your cleaned data.
4. Remove the Helper Column:
    . You can now delete the helper column (Column C) if you no longer need it.

This process will leave you with only the first occurrenc. Vof each language and remove all subsequent duplicates.

*/