#
#  docker build --build-arg ENV_TYPE=dev  --no-cache -t cbrodski/lambda_ffmpeg:official_v2_dev -f Dockerfile_ffmpeg  .      
#
#  ⤹ UNIQUE TO AWS IMAGES
#  docker run -it --entrypoint /bin/sh -e ENV=dev cbrodski/lambda_ffmpeg:official_v2_dev
#
#


# Use an official AWS Lambda base image
FROM public.ecr.aws/lambda/python:3.11

# Arguments
ARG ENV_TYPE=dev
ENV ENV=${ENV_TYPE}

###########
# Project #
###########
WORKDIR /app
# RUN apt update 
# RUN apt-get update
# RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata 
# RUN apt install git -y 
# RUN git clone https://github.com/Brodski/scraper-dl-vids.git 
WORKDIR /app
COPY BarbaraWalters.mp3 .


################
# Dependencies #
################
# WORKDIR /app/scraper-dl-vids/SSScrapey-rework/docker
# RUN if [ "${ENV}" = "dev" ]; then \
#         git fetch origin dev && \
#         git checkout dev && \
#         git reset --hard origin/dev && \
#         git pull origin dev --force; \
#     elif [ "${ENV}" = "prod" ]; then \
#         git reset --hard origin/master ; \
#         git pull origin master --force ; \
#         echo "Running in production mode" ; \
#     else \
#         echo "Unknown environment: ${ENV}" && exit 1; \
#     fi

#################
# Update Branch #
#################
# WORKDIR /app/scraper-dl-vids/SSScrapey-rework/docker
# COPY dock_setup.sh dock_setup.sh
# RUN chmod +x dock_setup.sh


# CMD echo "NOT DONE!!!!!!!!!!!!" ; \
#     cd /app/scraper-dl-vids/SSScrapey-rework/docker ; \
#     sh dock_setup.sh ; \
#     cd /app/scraper-dl-vids/MICROS_2_0 ; \
#     python kickDownloader.py ; \
#     echo "DONE!!!!!!!!!!!!" ; 
CMD ["ffmpeg_lambda.handler"]
