#
# docker build -t hello-lambda .
# docker run -p 9000:8080 hello-lambda:latest
#
# curl "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'
# Invoke-RestMethod -Uri "http://localhost:9000/2015-03-31/functions/function/invocations" -Method Post -Body '{}' -ContentType 'application/json'

FROM public.ecr.aws/lambda/nodejs:16

ENV IS_LAMBDA="true"

COPY app.js ${LAMBDA_TASK_ROOT}
COPY ../idontfront-app/public/             ${LAMBDA_TASK_ROOT}
COPY ../idontfront-app/routes/             ${LAMBDA_TASK_ROOT}
COPY ../idontfront-app/server-scripts/     ${LAMBDA_TASK_ROOT}
COPY ../idontfront-app/views/              ${LAMBDA_TASK_ROOT}
COPY ../idontfront-app/iDontFront-app.js   ${LAMBDA_TASK_ROOT}
COPY ../idontfront-app/configs.js          ${LAMBDA_TASK_ROOT}
# COPY src/* ${LAMBDA_TASK_ROOT}


CMD ["iDontFront-app.lambdaHandler"]

# aws lambda invoke --region eu-west-1 --endpoint http://localhost:8080 --no-sign-request --function-name function --cli-binary-format raw-in-base64-out --payload '{"a":"b"}' output.txt