FROM nvidia/cuda:12.0.1-runtime-ubuntu20.04 

WORKDIR /app
RUN apt update \
    && apt-get update \
    && apt install curl  -y \
    && apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev -y \
    && curl https://www.python.org/ftp/python/3.10.10/Python-3.10.10.tgz -o Python-3.10.10.tgz \
    && tar -xzf Python-3.10.10.tgz \
    && cd Python-3.10.10/ \
    && ./configure --enable-optimizations --with-ensurepip=install \
    && make -j $(nproc) \
    && make altinstall \
    && ln -s /usr/local/bin/python3.10 /usr/local/bin/python \
    && cd .. \
    && rm Python-3.10.10.tgz 


#######
# Pip #
#######    
WORKDIR /app
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
    && python get-pip.py pip==23.0.1 \
    && pip --version \
    && rm get-pip.py 



WORKDIR /app/scraper-dl-vids/audio2Text
# ENTRYPOINT ls && \
CMD ls && \
    echo "CONTAINER_ID= $CONTAINER_ID" && \
    echo "CONTAINER_ID= $CONTAINER_ID" && \
    echo "CONTAINER_ID= $CONTAINER_ID" && \
    echo ".vast_api_key= " && \
    cat ~/.vast_api_key ; \
    cat ~/.vast_containerlabel ; \
    pip install vastai && \ 
    cat ~/.ssh/authorized_keys | md5sum | awk '{print $1}' > ssh_key_hv ; \
    echo -n $VAST_CONTAINERLABEL | md5sum | awk '{print $1}' > instance_id_hv ; \
    head -c -1 -q ssh_key_hv instance_id_hv > ~/.vast_api_key ; \
    vastai destroy instance $CONTAINER_ID;
